import { MarkerType } from '@vue-flow/core';

export const STATIC_ROADMAPS_LIST = [
    {
        id: 'history-kazakhstan',
        title: 'История Казахстана 🇰🇿',
        author: 'AI Ассистент',
        created_at: new Date(2024, 0, 1).toISOString(),
        votes_sum: 150,
        participants_count: 75,
        description: 'Глубокое погружение в историю Казахстана от древности до современности.',
    },
    {
        id: 'quantum-physics',
        title: 'Основы Квантовой Физики ⚛️',
        author: 'AI Ассистент',
        created_at: new Date(2024, 1, 10).toISOString(),
        votes_sum: 210,
        participants_count: 90,
        description: 'Путешествие в удивительный мир квантовой механики.',
    },
    {
        id: 'web-development',
        title: 'Веб-разработка: Full Stack 💻',
        author: 'AI Ассистент',
        created_at: new Date(2024, 2, 15).toISOString(),
        votes_sum: 300,
        participants_count: 120,
        description: 'Станьте full-stack веб-разработчиком с нуля.',
    },
    {
        id: 'data-science-intro',
        title: 'Введение в Data Science 📊',
        author: 'AI Ассистент',
        created_at: new Date(2024, 3, 5).toISOString(),
        votes_sum: 180,
        participants_count: 65,
        description: 'Основы анализа данных, машинного обучения и визуализации.',
    },
    {
        id: 'philosophy-101',
        title: 'Философия: Ключевые концепции 🤔',
        author: 'AI Ассистент',
        created_at: new Date(2024, 4, 20).toISOString(),
        votes_sum: 120,
        participants_count: 50,
        description: 'Знакомство с великими мыслителями и их идеями.',
    },
    {
        id: 'learning-english-b2',
        title: 'Английский язык: Уровень B2 🇬🇧',
        author: 'AI Ассистент',
        created_at: new Date(2024, 5, 1).toISOString(),
        votes_sum: 250,
        participants_count: 110,
        description: 'Совершенствование навыков английского языка до уровня Upper-Intermediate.',
    }
];

export const INITIAL_NODES_DATA = {
    'history-kazakhstan': {
        nodes: [
            { id: 'hist-0', type: 'custom', label: 'История Казахстана', position: { x: 800, y: 50 }, data: { title: 'История Казахстана', tag: 'Старт', status: 'not_started', description: 'Обзорный узел курса.' } },
            { id: 'hist-1', type: 'custom', label: 'Древний мир', position: { x: 250, y: 200 }, data: { title: 'Древний мир (до V в.)', tag: 'Эпоха', status: 'not_started', description: 'Сакские племена, гунны, кангюи.' } },
            { id: 'hist-1-1', type: 'custom', label: 'Сакские племена', position: { x: 50, y: 350 }, data: { title: 'Сакские племена', tag: 'Культура', status: 'not_started', description: 'Образ жизни, искусство, завоевания.' } },
            { id: 'hist-1-2', type: 'custom', label: 'Гунны', position: { x: 250, y: 350 }, data: { title: 'Гунны', tag: 'Народ', status: 'not_started', description: 'Великое переселение народов.' } },
            { id: 'hist-1-3', type: 'custom', label: 'Кангюи', position: { x: 450, y: 350 }, data: { title: 'Государство Кангюй', tag: 'Государство', status: 'not_started', description: 'Политическое устройство и экономика.' } },
            { id: 'hist-1-4', type: 'custom', label: 'Усуни', position: { x: 150, y: 450 }, data: { title: 'Государство Усуней', tag: 'Государство', status: 'not_started', description: 'Семиречье, социальная структура.' } },


            { id: 'hist-2', type: 'custom', label: 'Средневековье', position: { x: 700, y: 200 }, data: { title: 'Средневековье (V-XV вв.)', tag: 'Эпоха', status: 'not_started', description: 'Тюркские каганаты, монгольское нашествие.' } },
            { id: 'hist-2-1', type: 'custom', label: 'Тюркский каганат', position: { x: 550, y: 350 }, data: { title: 'Тюркский каганат', tag: 'Государство', status: 'not_started', description: 'Западный и Восточный каганаты.' } },
            { id: 'hist-2-2', type: 'custom', label: 'Караханиды', position: { x: 700, y: 350 }, data: { title: 'Государство Караханидов', tag: 'Государство', status: 'not_started', description: 'Исламизация и культура.' } },
            { id: 'hist-2-3', type: 'custom', label: 'Золотая Орда', position: { x: 850, y: 350 }, data: { title: 'Золотая Орда', tag: 'Империя', status: 'not_started', description: 'Влияние на казахские племена.' } },
            { id: 'hist-2-4', type: 'custom', label: 'Государство Огузов', position: { x: 650, y: 450 }, data: { title: 'Государство Огузов (Ябгу)', tag: 'Государство', status: 'not_started', description: 'Низовья Сырдарьи, сельджуки.' } },


            { id: 'hist-3', type: 'custom', label: 'Казахское ханство', position: { x: 1150, y: 200 }, data: { title: 'Казахское ханство (XV-XVIII вв.)', tag: 'Эпоха', status: 'not_started', description: 'Образование, расцвет и борьба за независимость.' } },
            { id: 'hist-3-1', type: 'custom', label: 'Образование ханства', position: { x: 1000, y: 350 }, data: { title: 'Образование Казахского ханства', tag: 'Событие', status: 'not_started', description: 'Жанибек и Керей.' } },
            { id: 'hist-3-2', type: 'custom', label: 'Хан Касым', position: { x: 1150, y: 350 }, data: { title: 'Правление Хана Касыма', tag: 'Личность', status: 'not_started', description: '"Қасым ханның қасқа жолы".' } },
            { id: 'hist-3-3', type: 'custom', label: 'Абылай хан', position: { x: 1300, y: 350 }, data: { title: 'Эпоха Абылай хана', tag: 'Личность', status: 'not_started', description: 'Борьба с джунгарами, внешняя политика.' } },
            { id: 'hist-3-4', type: 'custom', label: 'Хан Тауке', position: { x: 1250, y: 450 }, data: { title: 'Правление Хана Тауке', tag: 'Личность', status: 'not_started', description: '"Жеты Жаргы" - свод законов.' } },

            { id: 'hist-4', type: 'custom', label: 'В составе Рос. Империи', position: { x: 400, y: 550 }, data: { title: 'В составе Российской Империи (XVIII-нач. XX в.)', tag: 'Период', status: 'not_started', description: 'Колонизация, восстания, реформы.' } },
            { id: 'hist-4-1', type: 'custom', label: 'Присоединение Младшего жуза', position: { x: 250, y: 700 }, data: { title: 'Присоединение Младшего жуза', tag: 'Процесс', status: 'not_started', description: 'Политические предпосылки и последствия.' } },
            { id: 'hist-4-2', type: 'custom', label: 'Восстание Кенесары Касымова', position: { x: 400, y: 700 }, data: { title: 'Восстание Кенесары Касымова', tag: 'Восстание', status: 'not_started', description: 'Крупнейшее антиколониальное движение.' } },
            { id: 'hist-4-3', type: 'custom', label: 'Алаш Орда', position: { x: 550, y: 700 }, data: { title: 'Движение Алаш', tag: 'Движение', status: 'not_started', description: 'Зарождение национальной интеллигенции.' } },
            { id: 'hist-4-4', type: 'custom', label: 'Реформы 1867-1868 гг.', position: { x: 350, y: 800 }, data: { title: 'Административные реформы', tag: 'Реформа', status: 'not_started', description: 'Изменение системы управления краем.' } },


            { id: 'hist-5', type: 'custom', label: 'Советский период', position: { x: 800, y: 550 }, data: { title: 'Советский период (1917-1991)', tag: 'Период', status: 'not_started', description: 'Революция, голод, индустриализация, ВОВ, целина, застой.' } },
            { id: 'hist-5-1', type: 'custom', label: 'Голод 1930-х (Ашаршылық)', position: { x: 650, y: 700 }, data: { title: 'Голод 1930-х (Ашаршылық)', tag: 'Трагедия', status: 'not_started', description: 'Причины, масштабы, последствия.' } },
            { id: 'hist-5-2', type: 'custom', label: 'Великая Отечественная Война', position: { x: 800, y: 700 }, data: { title: 'Казахстан в ВОВ', tag: 'Война', status: 'not_started', description: 'Вклад в победу, герои фронта и тыла.' } },
            { id: 'hist-5-3', type: 'custom', label: 'Декабрьские события 1986 (Желтоксан)', position: { x: 950, y: 700 }, data: { title: 'Желтоксан 1986', tag: 'Событие', status: 'not_started', description: 'Протесты молодежи в Алма-Ате.' } },
            { id: 'hist-5-4', type: 'custom', label: 'Индустриализация и коллективизация', position: { x: 750, y: 800 }, data: { title: 'Индустриализация и коллективизация', tag: 'Процесс', status: 'not_started', description: 'Изменение экономической структуры.' } },


            { id: 'hist-6', type: 'custom', label: 'Независимый Казахстан', position: { x: 1200, y: 550 }, data: { title: 'Независимый Казахстан (с 1991)', tag: 'Период', status: 'not_started', description: 'Становление государственности, реформы, современное развитие.' } },
            { id: 'hist-6-1', type: 'custom', label: 'Обретение независимости', position: { x: 1050, y: 700 }, data: { title: 'Обретение независимости', tag: 'Веха', status: 'not_started', description: 'Первые шаги суверенного государства.' } },
            { id: 'hist-6-2', type: 'custom', label: 'Конституция РК', position: { x: 1200, y: 700 }, data: { title: 'Конституция РК', tag: 'Закон', status: 'not_started', description: 'Основной закон страны, его эволюция.' } },
            { id: 'hist-6-3', type: 'custom', label: 'Современные вызовы', position: { x: 1350, y: 700 }, data: { title: 'Современные вызовы и перспективы', tag: 'Будущее', status: 'not_started', description: 'Экономика, политика, общество.' } },
            { id: 'hist-6-4', type: 'custom', label: 'Перенос столицы', position: { x: 1150, y: 800 }, data: { title: 'Перенос столицы в Астану', tag: 'Событие', status: 'not_started', description: 'Причины и значение переноса столицы.' } },
        ],
        edges: [
            { id: 'e-hist-0-1', source: 'hist-0', target: 'hist-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-0-2', source: 'hist-0', target: 'hist-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-0-3', source: 'hist-0', target: 'hist-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-0-4', source: 'hist-0', target: 'hist-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-0-5', source: 'hist-0', target: 'hist-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-0-6', source: 'hist-0', target: 'hist-6', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-1-1-1', source: 'hist-1', target: 'hist-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-1-1-2', source: 'hist-1', target: 'hist-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-1-1-3', source: 'hist-1', target: 'hist-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-1-1-4', source: 'hist-1', target: 'hist-1-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-2-2-1', source: 'hist-2', target: 'hist-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-2-2-2', source: 'hist-2', target: 'hist-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-2-2-3', source: 'hist-2', target: 'hist-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-2-2-4', source: 'hist-2', target: 'hist-2-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-3-3-1', source: 'hist-3', target: 'hist-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-3-3-2', source: 'hist-3', target: 'hist-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-3-3-3', source: 'hist-3', target: 'hist-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-3-3-4', source: 'hist-3', target: 'hist-3-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-4-4-1', source: 'hist-4', target: 'hist-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-4-4-2', source: 'hist-4', target: 'hist-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-4-4-3', source: 'hist-4', target: 'hist-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-4-4-4', source: 'hist-4', target: 'hist-4-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-5-5-1', source: 'hist-5', target: 'hist-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-5-5-2', source: 'hist-5', target: 'hist-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-5-5-3', source: 'hist-5', target: 'hist-5-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-5-5-4', source: 'hist-5', target: 'hist-5-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-6-6-1', source: 'hist-6', target: 'hist-6-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-6-6-2', source: 'hist-6', target: 'hist-6-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-6-6-3', source: 'hist-6', target: 'hist-6-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-hist-6-6-4', source: 'hist-6', target: 'hist-6-4', markerEnd: MarkerType.ArrowClosed },
        ],
    },
    'quantum-physics': {
        nodes: [
            { id: 'qp-0', type: 'custom', label: 'Основы Квантовой Физики', position: { x: 800, y: 25 }, data: { title: 'Основы Квантовой Физики', tag: 'Старт', status: 'not_started', description: 'Путеводитель по миру квантов.' } },
            { id: 'qp-1', type: 'custom', label: 'Истоки Квантовой Теории', position: { x: 400, y: 150 }, data: { title: 'Истоки Квантовой Теории', tag: 'Введение', status: 'not_started', description: 'Проблемы классической физики на рубеже XIX-XX веков.' } },
            { id: 'qp-1-1', type: 'custom', label: 'Излучение черного тела', position: { x: 200, y: 275 }, data: { title: 'Излучение абсолютно черного тела', tag: 'Эксперимент', status: 'not_started', description: 'Ультрафиолетовая катастрофа и гипотеза Планка.' } },
            { id: 'qp-1-2', type: 'custom', label: 'Фотоэффект', position: { x: 400, y: 275 }, data: { title: 'Фотоэлектрический эффект', tag: 'Эксперимент', status: 'not_started', description: 'Объяснение Эйнштейна, кванты света (фотоны).' } },
            { id: 'qp-1-3', type: 'custom', label: 'Атомные спектры', position: { x: 600, y: 275 }, data: { title: 'Линейчатые спектры атомов', tag: 'Эксперимент', status: 'not_started', description: 'Постулаты Бора и модель атома Бора.' } },

            { id: 'qp-2', type: 'custom', label: 'Волновая Механика', position: { x: 1000, y: 150 }, data: { title: 'Волновая Механика', tag: 'Основы', status: 'not_started', description: 'Двойственная природа материи.' } },
            { id: 'qp-2-1', type: 'custom', label: 'Гипотеза де Бройля', position: { x: 800, y: 275 }, data: { title: 'Волны де Бройля', tag: 'Теория', status: 'not_started', description: 'Корпускулярно-волновой дуализм для частиц.' } },
            { id: 'qp-2-2', type: 'custom', label: 'Уравнение Шрёдингера', position: { x: 1000, y: 275 }, data: { title: 'Уравнение Шрёдингера', tag: 'Уравнение', status: 'not_started', description: 'Стационарное и нестационарное уравнения, волновая функция.' } },
            { id: 'qp-2-3', type: 'custom', label: 'Принцип неопределенности', position: { x: 1200, y: 275 }, data: { title: 'Соотношения неопределенностей Гейзенберга', tag: 'Принцип', status: 'not_started', description: 'Фундаментальные ограничения на точность измерений.' } },

            { id: 'qp-3', type: 'custom', label: 'Квантовые Явления', position: { x: 400, y: 400 }, data: { title: 'Ключевые Квантовые Явления', tag: 'Эффекты', status: 'not_started', description: 'Проявления квантовой природы мира.' } },
            { id: 'qp-3-1', type: 'custom', label: 'Квантование энергии', position: { x: 200, y: 525 }, data: { title: 'Квантование энергии', tag: 'Концепция', status: 'not_started', description: 'Дискретные уровни энергии в атомах и молекулах.' } },
            { id: 'qp-3-2', type: 'custom', label: 'Туннельный эффект', position: { x: 400, y: 525 }, data: { title: 'Квантовое туннелирование', tag: 'Эффект', status: 'not_started', description: 'Прохождение частиц через потенциальные барьеры.' } },
            { id: 'qp-3-3', type: 'custom', label: 'Квантовая запутанность', position: { x: 600, y: 525 }, data: { title: 'Квантовая запутанность', tag: 'Феномен', status: 'not_started', description: '"Жуткое дальнодействие" Эйнштейна, парадокс ЭПР.' } },

            { id: 'qp-4', type: 'custom', label: 'Атом Водорода', position: { x: 1000, y: 400 }, data: { title: 'Квантовая теория атома водорода', tag: 'Применение', status: 'not_started', description: 'Точное решение уравнения Шрёдингера.' } },
            { id: 'qp-4-1', type: 'custom', label: 'Квантовые числа', position: { x: 800, y: 525 }, data: { title: 'Квантовые числа', tag: 'Описание', status: 'not_started', description: 'Главное, орбитальное, магнитное, спиновое.' } },
            { id: 'qp-4-2', type: 'custom', label: 'Атомные орбитали', position: { x: 1000, y: 525 }, data: { title: 'Атомные орбитали', tag: 'Структура', status: 'not_started', description: 's, p, d, f-орбитали, их форма и энергия.' } },
            { id: 'qp-4-3', type: 'custom', label: 'Принцип Паули', position: { x: 1200, y: 525 }, data: { title: 'Принцип запрета Паули', tag: 'Принцип', status: 'not_started', description: 'Заполнение электронных оболочек, фермионы.' } },

            { id: 'qp-5', type: 'custom', label: 'Современные приложения', position: { x: 800, y: 650 }, data: { title: 'Современные приложения квантовой физики', tag: 'Технологии', status: 'not_started', description: 'Как квантовая теория изменила мир.' } },
            { id: 'qp-5-1', type: 'custom', label: 'Лазеры', position: { x: 600, y: 775 }, data: { title: 'Лазеры', tag: 'Устройство', status: 'not_started', description: 'Принципы работы и применение.' } },
            { id: 'qp-5-2', type: 'custom', label: 'Полупроводники и транзисторы', position: { x: 800, y: 775 }, data: { title: 'Полупроводники и транзисторы', tag: 'Электроника', status: 'not_started', description: 'Основа современной электроники.' } },
            { id: 'qp-5-3', type: 'custom', label: 'Квантовые вычисления', position: { x: 1000, y: 775 }, data: { title: 'Квантовые вычисления и кубиты', tag: 'Будущее', status: 'not_started', description: 'Перспективы создания квантовых компьютеров.' } },
        ],
        edges: [
            { id: 'e-qp-0-1', source: 'qp-0', target: 'qp-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-0-2', source: 'qp-0', target: 'qp-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-1-1-1', source: 'qp-1', target: 'qp-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-1-1-2', source: 'qp-1', target: 'qp-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-1-1-3', source: 'qp-1', target: 'qp-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-2-2-1', source: 'qp-2', target: 'qp-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-2-2-2', source: 'qp-2', target: 'qp-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-2-2-3', source: 'qp-2', target: 'qp-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-0-3', source: 'qp-0', target: 'qp-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-3-3-1', source: 'qp-3', target: 'qp-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-3-3-2', source: 'qp-3', target: 'qp-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-3-3-3', source: 'qp-3', target: 'qp-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-0-4', source: 'qp-0', target: 'qp-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-4-4-1', source: 'qp-4', target: 'qp-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-4-4-2', source: 'qp-4', target: 'qp-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-4-4-3', source: 'qp-4', target: 'qp-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-0-5', source: 'qp-0', target: 'qp-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-5-5-1', source: 'qp-5', target: 'qp-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-5-5-2', source: 'qp-5', target: 'qp-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-qp-5-5-3', source: 'qp-5', target: 'qp-5-3', markerEnd: MarkerType.ArrowClosed },
        ]
    },
    'web-development': {
        nodes: [
            { id: 'wd-0', type: 'custom', label: 'Веб-разработка: Full Stack', position: { x: 800, y: 25 }, data: { title: 'Веб-разработка: Full Stack', tag: 'Старт', status: 'not_started', description: 'От HTML до развертывания вашего веб-приложения.' } },
            // Frontend
            { id: 'wd-1', type: 'custom', label: 'Основы Frontend', position: { x: 400, y: 150 }, data: { title: 'Основы Frontend', tag: 'Frontend', status: 'not_started', description: 'Базовые технологии для создания пользовательского интерфейса.' } },
            { id: 'wd-1-1', type: 'custom', label: 'HTML5', position: { x: 200, y: 275 }, data: { title: 'HTML5', tag: 'Разметка', status: 'not_started', description: 'Структура веб-страниц, семантика.' } },
            { id: 'wd-1-2', type: 'custom', label: 'CSS3', position: { x: 400, y: 275 }, data: { title: 'CSS3', tag: 'Стили', status: 'not_started', description: 'Стилизация, макеты (Flexbox, Grid), адаптивность.' } },
            { id: 'wd-1-3', type: 'custom', label: 'JavaScript Основы', position: { x: 600, y: 275 }, data: { title: 'JavaScript Основы', tag: 'Язык', status: 'not_started', description: 'Переменные, типы данных, функции, DOM, события.' } },
            // Advanced Frontend
            { id: 'wd-2', type: 'custom', label: 'Продвинутый Frontend', position: { x: 400, y: 400 }, data: { title: 'Продвинутый Frontend', tag: 'Frontend', status: 'not_started', description: 'Современные фреймворки и инструменты.' } },
            { id: 'wd-2-1', type: 'custom', label: 'JavaScript (ES6+)', position: { x: 150, y: 525 }, data: { title: 'JavaScript (ES6+)', tag: 'Язык', status: 'not_started', description: 'Классы, модули, промисы, async/await.' } },
            { id: 'wd-2-2', type: 'custom', label: 'Фреймворк (Vue/React/Angular)', position: { x: 400, y: 525 }, data: { title: 'Фреймворк (Vue/React/Angular)', tag: 'Фреймворк', status: 'not_started', description: 'Компоненты, состояние, роутинг. Выберите один.' } },
            { id: 'wd-2-3', type: 'custom', label: 'Инструменты сборки', position: { x: 650, y: 525 }, data: { title: 'Инструменты сборки (Webpack/Vite)', tag: 'Инструменты', status: 'not_started', description: 'Оптимизация, бандлинг, HMR.' } },
            // Backend
            { id: 'wd-3', type: 'custom', label: 'Основы Backend', position: { x: 1200, y: 150 }, data: { title: 'Основы Backend', tag: 'Backend', status: 'not_started', description: 'Серверная логика и базы данных.' } },
            { id: 'wd-3-1', type: 'custom', label: 'Язык Backend (Node.js/Python/Java/Go)', position: { x: 1000, y: 275 }, data: { title: 'Язык Backend (Node.js/Python/etc)', tag: 'Язык', status: 'not_started', description: 'Выберите один язык для серверной разработки.' } },
            { id: 'wd-3-2', type: 'custom', label: 'Фреймворк Backend (Express/Django/Spring)', position: { x: 1200, y: 275 }, data: { title: 'Фреймворк Backend', tag: 'Фреймворк', status: 'not_started', description: 'Соответствующий фреймворк для выбранного языка.' } },
            { id: 'wd-3-3', type: 'custom', label: 'Базы данных (SQL/NoSQL)', position: { x: 1400, y: 275 }, data: { title: 'Базы данных (SQL/NoSQL)', tag: 'БД', status: 'not_started', description: 'Основы реляционных и нереляционных БД.' } },
            // Advanced Backend
            { id: 'wd-4', type: 'custom', label: 'Продвинутый Backend', position: { x: 1200, y: 400 }, data: { title: 'Продвинутый Backend', tag: 'Backend', status: 'not_started', description: 'API, аутентификация, безопасность.' } },
            { id: 'wd-4-1', type: 'custom', label: 'RESTful API / GraphQL', position: { x: 950, y: 525 }, data: { title: 'RESTful API / GraphQL', tag: 'API', status: 'not_started', description: 'Проектирование и реализация API.' } },
            { id: 'wd-4-2', type: 'custom', label: 'Аутентификация и Авторизация', position: { x: 1200, y: 525 }, data: { title: 'Аутентификация и Авторизация', tag: 'Безопасность', status: 'not_started', description: 'JWT, OAuth, сессии.' } },
            { id: 'wd-4-3', type: 'custom', label: 'Контейнеризация (Docker)', position: { x: 1450, y: 525 }, data: { title: 'Контейнеризация (Docker)', tag: 'DevOps', status: 'not_started', description: 'Изоляция и развертывание приложений.' } },
            // Full Stack & DevOps
            { id: 'wd-5', type: 'custom', label: 'Full Stack & DevOps', position: { x: 800, y: 650 }, data: { title: 'Full Stack & DevOps', tag: 'Общее', status: 'not_started', description: 'Объединение всего и развертывание.' } },
            { id: 'wd-5-1', type: 'custom', label: 'Системы контроля версий (Git)', position: { x: 400, y: 775 }, data: { title: 'Системы контроля версий (Git)', tag: 'Инструменты', status: 'not_started', description: 'Ветвление, слияние, совместная работа.' } },
            { id: 'wd-5-2', type: 'custom', label: 'Тестирование (Unit, Integration)', position: { x: 650, y: 775 }, data: { title: 'Тестирование', tag: 'Качество', status: 'not_started', description: 'Обеспечение качества кода.' } },
            { id: 'wd-5-3', type: 'custom', label: 'CI/CD', position: { x: 900, y: 775 }, data: { title: 'CI/CD (Jenkins, GitHub Actions)', tag: 'DevOps', status: 'not_started', description: 'Автоматизация сборки и развертывания.' } },
            { id: 'wd-5-4', type: 'custom', label: 'Облачные платформы (AWS/Azure/GCP)', position: { x: 1150, y: 775 }, data: { title: 'Облачные платформы', tag: 'Хостинг', status: 'not_started', description: 'Развертывание приложений в облаке.' } },
        ],
        edges: [
            { id: 'e-wd-0-1', source: 'wd-0', target: 'wd-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-1-1-1', source: 'wd-1', target: 'wd-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-1-1-2', source: 'wd-1', target: 'wd-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-1-1-3', source: 'wd-1', target: 'wd-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-1-2', source: 'wd-1', target: 'wd-2', markerEnd: MarkerType.ArrowClosed, label: 'Далее' },
            { id: 'e-wd-2-2-1', source: 'wd-2', target: 'wd-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-2-2-2', source: 'wd-2', target: 'wd-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-2-2-3', source: 'wd-2', target: 'wd-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-0-3', source: 'wd-0', target: 'wd-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-3-3-1', source: 'wd-3', target: 'wd-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-3-3-2', source: 'wd-3', target: 'wd-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-3-3-3', source: 'wd-3', target: 'wd-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-3-4', source: 'wd-3', target: 'wd-4', markerEnd: MarkerType.ArrowClosed, label: 'Далее' },
            { id: 'e-wd-4-4-1', source: 'wd-4', target: 'wd-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-4-4-2', source: 'wd-4', target: 'wd-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-4-4-3', source: 'wd-4', target: 'wd-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-0-5', source: 'wd-0', target: 'wd-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-5-5-1', source: 'wd-5', target: 'wd-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-5-5-2', source: 'wd-5', target: 'wd-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-5-5-3', source: 'wd-5', target: 'wd-5-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-wd-5-5-4', source: 'wd-5', target: 'wd-5-4', markerEnd: MarkerType.ArrowClosed },
        ]
    },
    'data-science-intro': {
        nodes: [
            { id: 'ds-0', type: 'custom', label: 'Введение в Data Science', position: { x: 800, y: 25 }, data: { title: 'Введение в Data Science', tag: 'Старт', status: 'not_started', description: 'Путешествие в мир данных и аналитики.' } },
            // Основы
            { id: 'ds-1', type: 'custom', label: 'Математика и Статистика', position: { x: 400, y: 150 }, data: { title: 'Математика и Статистика', tag: 'Фундамент', status: 'not_started', description: 'Необходимая теоретическая база.' } },
            { id: 'ds-1-1', type: 'custom', label: 'Линейная алгебра', position: { x: 200, y: 275 }, data: { title: 'Линейная алгебра', tag: 'Математика', status: 'not_started', description: 'Векторы, матрицы, операции.' } },
            { id: 'ds-1-2', type: 'custom', label: 'Математический анализ', position: { x: 400, y: 275 }, data: { title: 'Математический анализ', tag: 'Математика', status: 'not_started', description: 'Производные, интегралы, оптимизация.' } },
            { id: 'ds-1-3', type: 'custom', label: 'Теория вероятностей и статистика', position: { x: 600, y: 275 }, data: { title: 'Теория вероятностей и статистика', tag: 'Статистика', status: 'not_started', description: 'Распределения, гипотезы, регрессия.' } },
            // Программирование
            { id: 'ds-2', type: 'custom', label: 'Программирование для DS', position: { x: 1000, y: 150 }, data: { title: 'Программирование для Data Science', tag: 'Инструменты', status: 'not_started', description: 'Языки и библиотеки.' } },
            { id: 'ds-2-1', type: 'custom', label: 'Python Основы', position: { x: 800, y: 275 }, data: { title: 'Python Основы', tag: 'Python', status: 'not_started', description: 'Синтаксис, структуры данных, функции.' } },
            { id: 'ds-2-2', type: 'custom', label: 'NumPy и Pandas', position: { x: 1000, y: 275 }, data: { title: 'NumPy и Pandas', tag: 'Python', status: 'not_started', description: 'Работа с массивами и таблицами данных.' } },
            { id: 'ds-2-3', type: 'custom', label: 'Визуализация (Matplotlib, Seaborn)', position: { x: 1200, y: 275 }, data: { title: 'Визуализация данных', tag: 'Python', status: 'not_started', description: 'Построение графиков и диаграмм.' } },
            // Машинное обучение
            { id: 'ds-3', type: 'custom', label: 'Основы Машинного Обучения', position: { x: 400, y: 425 }, data: { title: 'Основы Машинного Обучения (ML)', tag: 'ML', status: 'not_started', description: 'Основные концепции и алгоритмы.' } },
            { id: 'ds-3-1', type: 'custom', label: 'Введение в ML', position: { x: 150, y: 550 }, data: { title: 'Введение в ML', tag: 'ML', status: 'not_started', description: 'Типы задач (классификация, регрессия, кластеризация).' } },
            { id: 'ds-3-2', type: 'custom', label: 'Подготовка данных', position: { x: 325, y: 550 }, data: { title: 'Подготовка данных (Preprocessing)', tag: 'ML', status: 'not_started', description: 'Очистка, нормализация, выбор признаков.' } },
            { id: 'ds-3-3', type: 'custom', label: 'Обучение с учителем', position: { x: 500, y: 550 }, data: { title: 'Обучение с учителем', tag: 'ML', status: 'not_started', description: 'Линейная регрессия, логистическая регрессия, деревья решений.' } },
            { id: 'ds-3-4', type: 'custom', label: 'Обучение без учителя', position: { x: 675, y: 550 }, data: { title: 'Обучение без учителя', tag: 'ML', status: 'not_started', description: 'K-means, иерархическая кластеризация.' } },
            // Продвинутые темы и инструменты
            { id: 'ds-4', type: 'custom', label: 'Продвинутые темы в DS', position: { x: 1000, y: 425 }, data: { title: 'Продвинутые темы и инструменты', tag: 'Развитие', status: 'not_started', description: 'Углубление знаний.' } },
            { id: 'ds-4-1', type: 'custom', label: 'Scikit-learn', position: { x: 750, y: 550 }, data: { title: 'Scikit-learn', tag: 'Библиотека', status: 'not_started', description: 'Основная библиотека для ML на Python.' } },
            { id: 'ds-4-2', type: 'custom', label: 'Оценка моделей', position: { x: 925, y: 550 }, data: { title: 'Оценка моделей и метрики', tag: 'ML', status: 'not_started', description: 'Точность, полнота, F1-мера, ROC-AUC.' } },
            { id: 'ds-4-3', type: 'custom', label: 'Введение в Deep Learning', position: { x: 1100, y: 550 }, data: { title: 'Введение в Deep Learning', tag: 'DL', status: 'not_started', description: 'Нейронные сети, TensorFlow/Keras/PyTorch.' } },
            { id: 'ds-4-4', type: 'custom', label: 'Работа с большими данными (Big Data)', position: { x: 1275, y: 550 }, data: { title: 'Введение в Big Data', tag: 'BigData', status: 'not_started', description: 'Spark, Hadoop (обзорно).' } },
            // Проект и карьера
            { id: 'ds-5', type: 'custom', label: 'Проект и Карьера', position: { x: 800, y: 675 }, data: { title: 'Проектная работа и Карьера', tag: 'Практика', status: 'not_started', description: 'Применение знаний и развитие в профессии.' } },
            { id: 'ds-5-1', type: 'custom', label: 'Учебный проект по DS', position: { x: 600, y: 800 }, data: { title: 'Выполнение учебного проекта', tag: 'Проект', status: 'not_started', description: 'От постановки задачи до презентации результатов.' } },
            { id: 'ds-5-2', type: 'custom', label: 'Соревнования (Kaggle)', position: { x: 800, y: 800 }, data: { title: 'Участие в соревнованиях (Kaggle)', tag: 'Сообщество', status: 'not_started', description: 'Практический опыт и портфолио.' } },
            { id: 'ds-5-3', type: 'custom', label: 'Карьерные пути в DS', position: { x: 1000, y: 800 }, data: { title: 'Карьерные пути в Data Science', tag: 'Карьера', status: 'not_started', description: 'Data Analyst, Data Engineer, ML Engineer, Data Scientist.' } },
        ],
        edges: [
            { id: 'e-ds-0-1', source: 'ds-0', target: 'ds-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-1-1-1', source: 'ds-1', target: 'ds-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-1-1-2', source: 'ds-1', target: 'ds-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-1-1-3', source: 'ds-1', target: 'ds-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-0-2', source: 'ds-0', target: 'ds-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-2-2-1', source: 'ds-2', target: 'ds-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-2-2-2', source: 'ds-2', target: 'ds-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-2-2-3', source: 'ds-2', target: 'ds-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-0-3', source: 'ds-0', target: 'ds-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-3-3-1', source: 'ds-3', target: 'ds-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-3-3-2', source: 'ds-3', target: 'ds-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-3-3-3', source: 'ds-3', target: 'ds-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-3-3-4', source: 'ds-3', target: 'ds-3-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-0-4', source: 'ds-0', target: 'ds-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-4-4-1', source: 'ds-4', target: 'ds-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-4-4-2', source: 'ds-4', target: 'ds-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-4-4-3', source: 'ds-4', target: 'ds-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-4-4-4', source: 'ds-4', target: 'ds-4-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-0-5', source: 'ds-0', target: 'ds-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-5-5-1', source: 'ds-5', target: 'ds-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-5-5-2', source: 'ds-5', target: 'ds-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ds-5-5-3', source: 'ds-5', target: 'ds-5-3', markerEnd: MarkerType.ArrowClosed },
        ]
    },
    'philosophy-101': {
        nodes: [
            { id: 'ph-0', type: 'custom', label: 'Философия: Ключевые концепции', position: { x: 800, y: 25 }, data: { title: 'Философия: Ключевые концепции', tag: 'Старт', status: 'not_started', description: 'Обзор основных философских школ и идей.' } },
            // Античность
            { id: 'ph-1', type: 'custom', label: 'Античная философия', position: { x: 400, y: 150 }, data: { title: 'Античная философия (VI в. до н.э. - VI в. н.э.)', tag: 'Период', status: 'not_started', description: 'Зарождение философии в Древней Греции и Риме.' } },
            { id: 'ph-1-1', type: 'custom', label: 'Досократики', position: { x: 150, y: 275 }, data: { title: 'Досократики', tag: 'Школа', status: 'not_started', description: 'Фалес, Анаксимандр, Гераклит, Парменид, Демокрит.' } },
            { id: 'ph-1-2', type: 'custom', label: 'Сократ и Софисты', position: { x: 325, y: 275 }, data: { title: 'Сократ и Софисты', tag: 'Мыслители', status: 'not_started', description: 'Поворот к человеку, метод Сократа.' } },
            { id: 'ph-1-3', type: 'custom', label: 'Платон', position: { x: 500, y: 275 }, data: { title: 'Платон', tag: 'Философ', status: 'not_started', description: 'Учение об идеях, государство, диалоги.' } },
            { id: 'ph-1-4', type: 'custom', label: 'Аристотель', position: { x: 675, y: 275 }, data: { title: 'Аристотель', tag: 'Философ', status: 'not_started', description: 'Логика, метафизика, этика, политика.' } },
            // Средневековье
            { id: 'ph-2', type: 'custom', label: 'Средневековая философия', position: { x: 1000, y: 150 }, data: { title: 'Средневековая философия (V - XV вв.)', tag: 'Период', status: 'not_started', description: 'Связь с религией, схоластика.' } },
            { id: 'ph-2-1', type: 'custom', label: 'Патристика', position: { x: 800, y: 275 }, data: { title: 'Патристика', tag: 'Направление', status: 'not_started', description: 'Августин Блаженный: вера и разум.' } },
            { id: 'ph-2-2', type: 'custom', label: 'Схоластика', position: { x: 1000, y: 275 }, data: { title: 'Схоластика', tag: 'Направление', status: 'not_started', description: 'Фома Аквинский: систематизация теологии.' } },
            { id: 'ph-2-3', type: 'custom', label: 'Арабская философия', position: { x: 1200, y: 275 }, data: { title: 'Арабская философия', tag: 'Школа', status: 'not_started', description: 'Аль-Фараби, Ибн Сина, Ибн Рушд.' } },
            // Новое Время
            { id: 'ph-3', type: 'custom', label: 'Философия Нового Времени', position: { x: 400, y: 425 }, data: { title: 'Философия Нового Времени (XVII - XVIII вв.)', tag: 'Период', status: 'not_started', description: 'Рационализм, эмпиризм, Просвещение.' } },
            { id: 'ph-3-1', type: 'custom', label: 'Рационализм', position: { x: 150, y: 550 }, data: { title: 'Рационализм', tag: 'Направление', status: 'not_started', description: 'Рене Декарт, Бенедикт Спиноза, Готфрид Лейбниц.' } },
            { id: 'ph-3-2', type: 'custom', label: 'Эмпиризм', position: { x: 325, y: 550 }, data: { title: 'Эмпиризм', tag: 'Направление', status: 'not_started', description: 'Фрэнсис Бэкон, Джон Локк, Джордж Беркли, Дэвид Юм.' } },
            { id: 'ph-3-3', type: 'custom', label: 'Философия Просвещения', position: { x: 500, y: 550 }, data: { title: 'Философия Просвещения', tag: 'Движение', status: 'not_started', description: 'Вольтер, Руссо, Монтескье.' } },
            { id: 'ph-3-4', type: 'custom', label: 'Иммануил Кант', position: { x: 675, y: 550 }, data: { title: 'Иммануил Кант', tag: 'Философ', status: 'not_started', description: 'Критическая философия, категории, императив.' } },
            // XIX Век
            { id: 'ph-4', type: 'custom', label: 'Философия XIX века', position: { x: 1000, y: 425 }, data: { title: 'Философия XIX века', tag: 'Период', status: 'not_started', description: 'Классическая немецкая философия, позитивизм, марксизм.' } },
            { id: 'ph-4-1', type: 'custom', label: 'Гегель', position: { x: 750, y: 550 }, data: { title: 'Георг Вильгельм Фридрих Гегель', tag: 'Философ', status: 'not_started', description: 'Диалектика, абсолютный идеализм.' } },
            { id: 'ph-4-2', type: 'custom', label: 'Карл Маркс', position: { x: 925, y: 550 }, data: { title: 'Карл Маркс и Фридрих Энгельс', tag: 'Теория', status: 'not_started', description: 'Исторический материализм, классовая борьба.' } },
            { id: 'ph-4-3', type: 'custom', label: 'Позитивизм', position: { x: 1100, y: 550 }, data: { title: 'Позитивизм', tag: 'Направление', status: 'not_started', description: 'Огюст Конт, Джон Стюарт Милль.' } },
            { id: 'ph-4-4', type: 'custom', label: 'Философия жизни', position: { x: 1275, y: 550 }, data: { title: 'Философия жизни', tag: 'Направление', status: 'not_started', description: 'Артур Шопенгауэр, Фридрих Ницше.' } },
            // XX Век и Современность
            { id: 'ph-5', type: 'custom', label: 'Философия XX века и Современность', position: { x: 800, y: 675 }, data: { title: 'Философия XX века и Современность', tag: 'Период', status: 'not_started', description: 'Экзистенциализм, феноменология, постмодернизм.' } },
            { id: 'ph-5-1', type: 'custom', label: 'Экзистенциализм', position: { x: 500, y: 800 }, data: { title: 'Экзистенциализм', tag: 'Направление', status: 'not_started', description: 'Сартр, Камю, Хайдеггер, Ясперс.' } },
            { id: 'ph-5-2', type: 'custom', label: 'Аналитическая философия', position: { x: 700, y: 800 }, data: { title: 'Аналитическая философия', tag: 'Школа', status: 'not_started', description: 'Рассел, Витгенштейн, логический позитивизм.' } },
            { id: 'ph-5-3', type: 'custom', label: 'Феноменология', position: { x: 900, y: 800 }, data: { title: 'Феноменология', tag: 'Метод', status: 'not_started', description: 'Эдмунд Гуссерль, Морис Мерло-Понти.' } },
            { id: 'ph-5-4', type: 'custom', label: 'Постмодернизм', position: { x: 1100, y: 800 }, data: { title: 'Постмодернизм', tag: 'Течение', status: 'not_started', description: 'Фуко, Деррида, Лиотар.' } },
        ],
        edges: [
            { id: 'e-ph-0-1', source: 'ph-0', target: 'ph-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-1-1-1', source: 'ph-1', target: 'ph-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-1-1-2', source: 'ph-1', target: 'ph-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-1-1-3', source: 'ph-1', target: 'ph-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-1-1-4', source: 'ph-1', target: 'ph-1-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-0-2', source: 'ph-0', target: 'ph-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-2-2-1', source: 'ph-2', target: 'ph-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-2-2-2', source: 'ph-2', target: 'ph-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-2-2-3', source: 'ph-2', target: 'ph-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-0-3', source: 'ph-0', target: 'ph-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-3-3-1', source: 'ph-3', target: 'ph-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-3-3-2', source: 'ph-3', target: 'ph-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-3-3-3', source: 'ph-3', target: 'ph-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-3-3-4', source: 'ph-3', target: 'ph-3-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-0-4', source: 'ph-0', target: 'ph-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-4-4-1', source: 'ph-4', target: 'ph-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-4-4-2', source: 'ph-4', target: 'ph-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-4-4-3', source: 'ph-4', target: 'ph-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-4-4-4', source: 'ph-4', target: 'ph-4-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-0-5', source: 'ph-0', target: 'ph-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-5-5-1', source: 'ph-5', target: 'ph-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-5-5-2', source: 'ph-5', target: 'ph-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-5-5-3', source: 'ph-5', target: 'ph-5-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-ph-5-5-4', source: 'ph-5', target: 'ph-5-4', markerEnd: MarkerType.ArrowClosed },
        ]
    },
    'learning-english-b2': {
        nodes: [
            { id: 'en-0', type: 'custom', label: 'Английский язык: Уровень B2', position: { x: 800, y: 25 }, data: { title: 'Английский язык: Уровень B2 (Upper-Intermediate)', tag: 'Старт', status: 'not_started', description: 'Путь к уверенному владению английским.' } },
            // Грамматика
            { id: 'en-1', type: 'custom', label: 'Грамматика (Grammar)', position: { x: 400, y: 150 }, data: { title: 'Грамматика B2', tag: 'Grammar', status: 'not_started', description: 'Углубленное изучение грамматических конструкций.' } },
            { id: 'en-1-1', type: 'custom', label: 'Времена глаголов (Tenses)', position: { x: 100, y: 275 }, data: { title: 'Все времена (Обзор и нюансы)', tag: 'Tenses', status: 'not_started', description: 'Perfect Continuous, Future Perfect, смешанные типы условных.' } },
            { id: 'en-1-2', type: 'custom', label: 'Модальные глаголы', position: { x: 275, y: 275 }, data: { title: 'Модальные глаголы (Продвинутый уровень)', tag: 'Modals', status: 'not_started', description: 'Выражение вероятности, сожаления, критики.' } },
            { id: 'en-1-3', type: 'custom', label: 'Пассивный залог', position: { x: 450, y: 275 }, data: { title: 'Пассивный залог (Все аспекты)', tag: 'Passive', status: 'not_started', description: 'Конструкции с инфинитивом и герундием.' } },
            { id: 'en-1-4', type: 'custom', label: 'Косвенная речь', position: { x: 625, y: 275 }, data: { title: 'Косвенная речь (Reported Speech)', tag: 'Reporting', status: 'not_started', description: 'Передача вопросов, приказов, сложных утверждений.' } },
            // Лексика
            { id: 'en-2', type: 'custom', label: 'Лексика (Vocabulary)', position: { x: 1000, y: 150 }, data: { title: 'Лексика B2', tag: 'Vocabulary', status: 'not_started', description: 'Расширение словарного запаса.' } },
            { id: 'en-2-1', type: 'custom', label: 'Фразовые глаголы', position: { x: 775, y: 275 }, data: { title: 'Фразовые глаголы (Частоупотребимые)', tag: 'Phrasal Verbs', status: 'not_started', description: 'Систематическое изучение и практика.' } },
            { id: 'en-2-2', type: 'custom', label: 'Идиомы и устойчивые выражения', position: { x: 950, y: 275 }, data: { title: 'Идиомы и устойчивые выражения', tag: 'Idioms', status: 'not_started', description: 'Понимание и использование в речи.' } },
            { id: 'en-2-3', type: 'custom', label: 'Словообразование', position: { x: 1125, y: 275 }, data: { title: 'Словообразование (Word Formation)', tag: 'Affixes', status: 'not_started', description: 'Суффиксы, префиксы, конверсия.' } },
            { id: 'en-2-4', type: 'custom', label: 'Тематическая лексика', position: { x: 1300, y: 275 }, data: { title: 'Тематическая лексика', tag: 'Topics', status: 'not_started', description: 'Работа, путешествия, технологии, окружающая среда и др.' } },
            // Чтение
            { id: 'en-3', type: 'custom', label: 'Чтение (Reading)', position: { x: 400, y: 425 }, data: { title: 'Навыки Чтения B2', tag: 'Reading', status: 'not_started', description: 'Понимание сложных текстов.' } },
            { id: 'en-3-1', type: 'custom', label: 'Чтение аутентичных текстов', position: { x: 200, y: 550 }, data: { title: 'Чтение статей, новостей, блогов', tag: 'Authentic', status: 'not_started', description: 'Развитие скорости и понимания.' } },
            { id: 'en-3-2', type: 'custom', label: 'Понимание основной идеи и деталей', position: { x: 400, y: 550 }, data: { title: 'Skimming & Scanning', tag: 'Skills', status: 'not_started', description: 'Быстрый просмотр и поиск информации.' } },
            { id: 'en-3-3', type: 'custom', label: 'Анализ текста', position: { x: 600, y: 550 }, data: { title: 'Анализ текста (авторская позиция, подтекст)', tag: 'Analysis', status: 'not_started', description: 'Чтение между строк.' } },
            // Аудирование
            { id: 'en-4', type: 'custom', label: 'Аудирование (Listening)', position: { x: 1000, y: 425 }, data: { title: 'Навыки Аудирования B2', tag: 'Listening', status: 'not_started', description: 'Понимание речи на слух.' } },
            { id: 'en-4-1', type: 'custom', label: 'Прослушивание подкастов и интервью', position: { x: 800, y: 550 }, data: { title: 'Прослушивание подкастов, интервью, лекций', tag: 'Authentic', status: 'not_started', description: 'Разные акценты и темпы речи.' } },
            { id: 'en-4-2', type: 'custom', label: 'Понимание основной информации и деталей', position: { x: 1000, y: 550 }, data: { title: 'Понимание основной информации и специфических деталей', tag: 'Skills', status: 'not_started', description: 'Умение выделять главное.' } },
            { id: 'en-4-3', type: 'custom', label: 'Различение мнений и фактов', position: { x: 1200, y: 550 }, data: { title: 'Различение мнений, фактов, эмоций', tag: 'Comprehension', status: 'not_started', description: 'Анализ услышанного.' } },
            // Говорение и Письмо
            { id: 'en-5', type: 'custom', label: 'Говорение и Письмо (Speaking & Writing)', position: { x: 800, y: 675 }, data: { title: 'Активные Навыки B2', tag: 'Productive Skills', status: 'not_started', description: 'Уверенное выражение мыслей.' } },
            { id: 'en-5-1', type: 'custom', label: 'Участие в дискуссиях', position: { x: 450, y: 800 }, data: { title: 'Участие в дискуссиях и дебатах', tag: 'Speaking', status: 'not_started', description: 'Аргументация, выражение мнения.' } },
            { id: 'en-5-2', type: 'custom', label: 'Презентации и монологи', position: { x: 650, y: 800 }, data: { title: 'Подготовка и проведение презентаций', tag: 'Speaking', status: 'not_started', description: 'Структурированное изложение мыслей.' } },
            { id: 'en-5-3', type: 'custom', label: 'Написание эссе и отчетов', position: { x: 850, y: 800 }, data: { title: 'Написание эссе, отчетов, обзоров', tag: 'Writing', status: 'not_started', description: 'Структура, стиль, аргументация.' } },
            { id: 'en-5-4', type: 'custom', label: 'Деловая переписка', position: { x: 1050, y: 800 }, data: { title: 'Официальная и неофициальная переписка', tag: 'Writing', status: 'not_started', description: 'Email, письма.' } },
        ],
        edges: [
            { id: 'e-en-0-1', source: 'en-0', target: 'en-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-1-1-1', source: 'en-1', target: 'en-1-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-1-1-2', source: 'en-1', target: 'en-1-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-1-1-3', source: 'en-1', target: 'en-1-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-1-1-4', source: 'en-1', target: 'en-1-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-0-2', source: 'en-0', target: 'en-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-2-2-1', source: 'en-2', target: 'en-2-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-2-2-2', source: 'en-2', target: 'en-2-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-2-2-3', source: 'en-2', target: 'en-2-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-2-2-4', source: 'en-2', target: 'en-2-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-0-3', source: 'en-0', target: 'en-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-3-3-1', source: 'en-3', target: 'en-3-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-3-3-2', source: 'en-3', target: 'en-3-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-3-3-3', source: 'en-3', target: 'en-3-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-0-4', source: 'en-0', target: 'en-4', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-4-4-1', source: 'en-4', target: 'en-4-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-4-4-2', source: 'en-4', target: 'en-4-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-4-4-3', source: 'en-4', target: 'en-4-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-0-5', source: 'en-0', target: 'en-5', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-5-5-1', source: 'en-5', target: 'en-5-1', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-5-5-2', source: 'en-5', target: 'en-5-2', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-5-5-3', source: 'en-5', target: 'en-5-3', markerEnd: MarkerType.ArrowClosed },
            { id: 'e-en-5-5-4', source: 'en-5', target: 'en-5-4', markerEnd: MarkerType.ArrowClosed },
        ]
    }
};